#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD)	+= devices_lge.o
obj-$(CONFIG_MACH_LGE_I_BOARD_ATNT)	+= i_atnt/
#obj-$(CONFIG_MACH_LGE_HDK_8x60)		+= hdk_8x60/
obj-$(CONFIG_MACH_LGE_I_BOARD_SKT)	+= i_skt/
obj-$(CONFIG_MACH_LGE_I_BOARD_DCM)      += i_dcm/
obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= i_lgu/
obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= i_vzw/
